// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: clients/pkg/promtail/targets/tokio/proto/async_ops/async_ops.proto

package async_ops

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_sortkeys "github.com/gogo/protobuf/sortkeys"
	_ "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	common "github.com/grafana/loki/clients/pkg/promtail/targets/tokio/proto/common"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// An AsyncOp state update.
//
// An async operation is a an operation that is associated with a resource
// This could, for example, be a a read or write on a TCP stream or a receive operation on
// a channel.
type AsyncOpUpdate struct {
	// A list of new async operations that were created since the last `AsyncOpUpdate`
	// was sent. Note that the fact that an async operation has been created
	// does not mean that is has been polled or is being polled. This information
	// is reflected in the Stats of the operation.
	NewAsyncOps []*AsyncOp `protobuf:"bytes,1,rep,name=new_async_ops,json=newAsyncOps,proto3" json:"new_async_ops,omitempty"`
	// Any async op stats that have changed since the last update.
	StatsUpdate map[uint64]*Stats `protobuf:"bytes,2,rep,name=stats_update,json=statsUpdate,proto3" json:"stats_update,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *AsyncOpUpdate) Reset()      { *m = AsyncOpUpdate{} }
func (*AsyncOpUpdate) ProtoMessage() {}
func (*AsyncOpUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cdbb1340b25742f, []int{0}
}
func (m *AsyncOpUpdate) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AsyncOpUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AsyncOpUpdate.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AsyncOpUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AsyncOpUpdate.Merge(m, src)
}
func (m *AsyncOpUpdate) XXX_Size() int {
	return m.Size()
}
func (m *AsyncOpUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_AsyncOpUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_AsyncOpUpdate proto.InternalMessageInfo

func (m *AsyncOpUpdate) GetNewAsyncOps() []*AsyncOp {
	if m != nil {
		return m.NewAsyncOps
	}
	return nil
}

func (m *AsyncOpUpdate) GetStatsUpdate() map[uint64]*Stats {
	if m != nil {
		return m.StatsUpdate
	}
	return nil
}

type AsyncOp struct {
	// The async op's ID.
	//
	// This uniquely identifies this op across all *currently live*
	// ones.
	Id *common.Id `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The numeric ID of the op's `Metadata`.
	//
	// This identifies the `Metadata` that describes the `tracing` span
	// corresponding to this async op. The metadata for this ID will have been sent
	// in a prior `RegisterMetadata` message.
	Metadata *common.MetaId `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// The source of this async operation. Most commonly this should be the name
	// of the method where the instantiation of this op has happened.
	Source string `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
}

func (m *AsyncOp) Reset()      { *m = AsyncOp{} }
func (*AsyncOp) ProtoMessage() {}
func (*AsyncOp) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cdbb1340b25742f, []int{1}
}
func (m *AsyncOp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AsyncOp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AsyncOp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AsyncOp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AsyncOp.Merge(m, src)
}
func (m *AsyncOp) XXX_Size() int {
	return m.Size()
}
func (m *AsyncOp) XXX_DiscardUnknown() {
	xxx_messageInfo_AsyncOp.DiscardUnknown(m)
}

var xxx_messageInfo_AsyncOp proto.InternalMessageInfo

func (m *AsyncOp) GetId() *common.Id {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *AsyncOp) GetMetadata() *common.MetaId {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *AsyncOp) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

type Stats struct {
	// Timestamp of when the async op has been created.
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Timestamp of when the async op was dropped.
	DroppedAt *timestamp.Timestamp `protobuf:"bytes,2,opt,name=dropped_at,json=droppedAt,proto3" json:"dropped_at,omitempty"`
	// The resource Id this `AsyncOp` is associated with. Note that both
	// `resource_id` and `task_id` can be None if this async op has not been polled yet
	ResourceId *common.Id `protobuf:"bytes,3,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	// The Id of the task that is awaiting on this op.
	TaskId *common.Id `protobuf:"bytes,4,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// Contains the operation poll stats.
	PollStats *common.PollStats `protobuf:"bytes,5,opt,name=poll_stats,json=pollStats,proto3" json:"poll_stats,omitempty"`
}

func (m *Stats) Reset()      { *m = Stats{} }
func (*Stats) ProtoMessage() {}
func (*Stats) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cdbb1340b25742f, []int{2}
}
func (m *Stats) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Stats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Stats.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Stats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stats.Merge(m, src)
}
func (m *Stats) XXX_Size() int {
	return m.Size()
}
func (m *Stats) XXX_DiscardUnknown() {
	xxx_messageInfo_Stats.DiscardUnknown(m)
}

var xxx_messageInfo_Stats proto.InternalMessageInfo

func (m *Stats) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Stats) GetDroppedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DroppedAt
	}
	return nil
}

func (m *Stats) GetResourceId() *common.Id {
	if m != nil {
		return m.ResourceId
	}
	return nil
}

func (m *Stats) GetTaskId() *common.Id {
	if m != nil {
		return m.TaskId
	}
	return nil
}

func (m *Stats) GetPollStats() *common.PollStats {
	if m != nil {
		return m.PollStats
	}
	return nil
}

func init() {
	proto.RegisterType((*AsyncOpUpdate)(nil), "async_ops.AsyncOpUpdate")
	proto.RegisterMapType((map[uint64]*Stats)(nil), "async_ops.AsyncOpUpdate.StatsUpdateEntry")
	proto.RegisterType((*AsyncOp)(nil), "async_ops.AsyncOp")
	proto.RegisterType((*Stats)(nil), "async_ops.Stats")
}

func init() {
	proto.RegisterFile("clients/pkg/promtail/targets/tokio/proto/async_ops/async_ops.proto", fileDescriptor_1cdbb1340b25742f)
}

var fileDescriptor_1cdbb1340b25742f = []byte{
	// 518 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x31, 0x8f, 0xd3, 0x4c,
	0x10, 0xf5, 0x3a, 0x97, 0xdc, 0x97, 0xf5, 0x77, 0x28, 0x2c, 0x12, 0x8a, 0x52, 0xac, 0xa2, 0x20,
	0xa1, 0x1c, 0x48, 0x36, 0x0a, 0x12, 0x02, 0xba, 0x9c, 0x44, 0x11, 0x04, 0xe2, 0x64, 0xa0, 0xa1,
	0xb1, 0x36, 0xd9, 0x3d, 0xb3, 0x8a, 0xed, 0xb5, 0xbc, 0x63, 0x4e, 0xe9, 0x8e, 0x7f, 0xc0, 0xcf,
	0xe0, 0xa7, 0x50, 0xa6, 0xbc, 0x92, 0x38, 0x05, 0x94, 0xf7, 0x13, 0x90, 0xbd, 0x76, 0x02, 0x77,
	0x05, 0xa2, 0xf2, 0xf3, 0xbc, 0xf7, 0xe6, 0x8d, 0x67, 0x64, 0x7c, 0xb2, 0x88, 0xa4, 0x48, 0x40,
	0x7b, 0xe9, 0x32, 0xf4, 0xd2, 0x4c, 0xc5, 0xc0, 0x64, 0xe4, 0x01, 0xcb, 0x42, 0x01, 0xda, 0x03,
	0xb5, 0x94, 0xaa, 0x2c, 0x83, 0xf2, 0x98, 0x5e, 0x25, 0x8b, 0x40, 0xa5, 0x7a, 0x8f, 0xdc, 0x8a,
	0x21, 0xdd, 0x5d, 0x61, 0x70, 0x1c, 0x2a, 0x15, 0x46, 0xc2, 0x58, 0xe6, 0xf9, 0x99, 0x07, 0x32,
	0x16, 0x1a, 0x58, 0x9c, 0xee, 0x91, 0x71, 0x0d, 0xe8, 0x75, 0x29, 0xcf, 0x33, 0x06, 0x52, 0x25,
	0x35, 0x7f, 0x67, 0xa1, 0xe2, 0x58, 0x25, 0x9e, 0x79, 0x98, 0xe2, 0xe8, 0x07, 0xc2, 0x47, 0xd3,
	0x32, 0xed, 0x4d, 0xfa, 0x3e, 0xe5, 0x0c, 0x04, 0x79, 0x82, 0x8f, 0x12, 0x71, 0x1e, 0xec, 0x46,
	0xe8, 0xa3, 0x61, 0x6b, 0xec, 0x4c, 0x88, 0xbb, 0x9f, 0xb2, 0x36, 0xf8, 0x4e, 0x22, 0xce, 0x6b,
	0xac, 0xc9, 0x2b, 0xfc, 0xbf, 0x06, 0x06, 0x3a, 0xc8, 0xab, 0x3e, 0x7d, 0xbb, 0xb2, 0x1d, 0xdf,
	0xb4, 0x99, 0x1c, 0xf7, 0x6d, 0x29, 0x36, 0xf8, 0x45, 0x02, 0xd9, 0xca, 0x77, 0xf4, 0xbe, 0x32,
	0x38, 0xc5, 0xbd, 0xeb, 0x02, 0xd2, 0xc3, 0xad, 0xa5, 0x58, 0xf5, 0xd1, 0x10, 0x8d, 0x0f, 0xfc,
	0x12, 0x92, 0xfb, 0xb8, 0xfd, 0x89, 0x45, 0x79, 0x19, 0x86, 0xc6, 0xce, 0xa4, 0xf7, 0x5b, 0x58,
	0xe5, 0xf6, 0x0d, 0xfd, 0xdc, 0x7e, 0x8a, 0x46, 0x12, 0x1f, 0xd6, 0x03, 0x90, 0x01, 0xb6, 0x25,
	0xaf, 0xfa, 0x38, 0x13, 0xec, 0xd6, 0xfb, 0x98, 0x71, 0xdf, 0x96, 0x9c, 0x3c, 0xc0, 0xff, 0xc5,
	0x02, 0x18, 0x67, 0xc0, 0xea, 0xae, 0xb7, 0x1a, 0xc5, 0x6b, 0x01, 0x6c, 0xc6, 0xfd, 0x1d, 0x4f,
	0xee, 0xe2, 0x8e, 0x56, 0x79, 0xb6, 0x10, 0xfd, 0xd6, 0x10, 0x8d, 0xbb, 0x7e, 0xfd, 0x36, 0xfa,
	0x6c, 0xe3, 0x76, 0x95, 0x4f, 0x9e, 0x61, 0xbc, 0xc8, 0x04, 0x03, 0xc1, 0x03, 0x06, 0x75, 0xe2,
	0xc0, 0x35, 0x87, 0x72, 0x9b, 0x43, 0xb9, 0xef, 0x9a, 0x4b, 0xfa, 0xdd, 0x5a, 0x3d, 0x85, 0xd2,
	0xca, 0x33, 0x95, 0xa6, 0xc6, 0x6a, 0xff, 0xdd, 0x5a, 0xab, 0xa7, 0x40, 0x1e, 0x62, 0x27, 0x13,
	0x66, 0x96, 0x40, 0xf2, 0x6a, 0xb8, 0x3f, 0x3f, 0x14, 0x37, 0xf4, 0x8c, 0x93, 0x7b, 0xf8, 0x10,
	0x98, 0x5e, 0x96, 0xc2, 0x83, 0x1b, 0xc2, 0x4e, 0x49, 0xcd, 0x38, 0x79, 0x84, 0x71, 0xaa, 0xa2,
	0x28, 0xa8, 0x4e, 0xd4, 0x6f, 0x57, 0xba, 0xdb, 0x8d, 0xee, 0x54, 0x45, 0x91, 0x59, 0x77, 0x37,
	0x6d, 0xe0, 0xc9, 0x05, 0x5a, 0x6f, 0xa8, 0x75, 0xb9, 0xa1, 0xd6, 0xd5, 0x86, 0xa2, 0x8b, 0x82,
	0xa2, 0xaf, 0x05, 0x45, 0xdf, 0x0a, 0x8a, 0xd6, 0x05, 0x45, 0xdf, 0x0b, 0x8a, 0x7e, 0x16, 0xd4,
	0xba, 0x2a, 0x28, 0xfa, 0xb2, 0xa5, 0xd6, 0x7a, 0x4b, 0xad, 0xcb, 0x2d, 0xb5, 0x3e, 0xbc, 0x0c,
	0x25, 0x7c, 0xcc, 0xe7, 0x65, 0x6b, 0x2f, 0xcc, 0xd8, 0x19, 0x4b, 0x98, 0x17, 0xa9, 0xa5, 0xf4,
	0xfe, 0xfd, 0xb7, 0x9a, 0x77, 0xaa, 0xc2, 0xe3, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xbe, 0x3c,
	0x64, 0x8d, 0x93, 0x03, 0x00, 0x00,
}

func (this *AsyncOpUpdate) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*AsyncOpUpdate)
	if !ok {
		that2, ok := that.(AsyncOpUpdate)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.NewAsyncOps) != len(that1.NewAsyncOps) {
		return false
	}
	for i := range this.NewAsyncOps {
		if !this.NewAsyncOps[i].Equal(that1.NewAsyncOps[i]) {
			return false
		}
	}
	if len(this.StatsUpdate) != len(that1.StatsUpdate) {
		return false
	}
	for i := range this.StatsUpdate {
		if !this.StatsUpdate[i].Equal(that1.StatsUpdate[i]) {
			return false
		}
	}
	return true
}
func (this *AsyncOp) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*AsyncOp)
	if !ok {
		that2, ok := that.(AsyncOp)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Id.Equal(that1.Id) {
		return false
	}
	if !this.Metadata.Equal(that1.Metadata) {
		return false
	}
	if this.Source != that1.Source {
		return false
	}
	return true
}
func (this *Stats) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Stats)
	if !ok {
		that2, ok := that.(Stats)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.CreatedAt.Equal(that1.CreatedAt) {
		return false
	}
	if !this.DroppedAt.Equal(that1.DroppedAt) {
		return false
	}
	if !this.ResourceId.Equal(that1.ResourceId) {
		return false
	}
	if !this.TaskId.Equal(that1.TaskId) {
		return false
	}
	if !this.PollStats.Equal(that1.PollStats) {
		return false
	}
	return true
}
func (this *AsyncOpUpdate) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&async_ops.AsyncOpUpdate{")
	if this.NewAsyncOps != nil {
		s = append(s, "NewAsyncOps: "+fmt.Sprintf("%#v", this.NewAsyncOps)+",\n")
	}
	keysForStatsUpdate := make([]uint64, 0, len(this.StatsUpdate))
	for k, _ := range this.StatsUpdate {
		keysForStatsUpdate = append(keysForStatsUpdate, k)
	}
	github_com_gogo_protobuf_sortkeys.Uint64s(keysForStatsUpdate)
	mapStringForStatsUpdate := "map[uint64]*Stats{"
	for _, k := range keysForStatsUpdate {
		mapStringForStatsUpdate += fmt.Sprintf("%#v: %#v,", k, this.StatsUpdate[k])
	}
	mapStringForStatsUpdate += "}"
	if this.StatsUpdate != nil {
		s = append(s, "StatsUpdate: "+mapStringForStatsUpdate+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *AsyncOp) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&async_ops.AsyncOp{")
	if this.Id != nil {
		s = append(s, "Id: "+fmt.Sprintf("%#v", this.Id)+",\n")
	}
	if this.Metadata != nil {
		s = append(s, "Metadata: "+fmt.Sprintf("%#v", this.Metadata)+",\n")
	}
	s = append(s, "Source: "+fmt.Sprintf("%#v", this.Source)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *Stats) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 9)
	s = append(s, "&async_ops.Stats{")
	if this.CreatedAt != nil {
		s = append(s, "CreatedAt: "+fmt.Sprintf("%#v", this.CreatedAt)+",\n")
	}
	if this.DroppedAt != nil {
		s = append(s, "DroppedAt: "+fmt.Sprintf("%#v", this.DroppedAt)+",\n")
	}
	if this.ResourceId != nil {
		s = append(s, "ResourceId: "+fmt.Sprintf("%#v", this.ResourceId)+",\n")
	}
	if this.TaskId != nil {
		s = append(s, "TaskId: "+fmt.Sprintf("%#v", this.TaskId)+",\n")
	}
	if this.PollStats != nil {
		s = append(s, "PollStats: "+fmt.Sprintf("%#v", this.PollStats)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringAsyncOps(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *AsyncOpUpdate) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AsyncOpUpdate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AsyncOpUpdate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.StatsUpdate) > 0 {
		for k := range m.StatsUpdate {
			v := m.StatsUpdate[k]
			baseI := i
			if v != nil {
				{
					size, err := v.MarshalToSizedBuffer(dAtA[:i])
					if err != nil {
						return 0, err
					}
					i -= size
					i = encodeVarintAsyncOps(dAtA, i, uint64(size))
				}
				i--
				dAtA[i] = 0x12
			}
			i = encodeVarintAsyncOps(dAtA, i, uint64(k))
			i--
			dAtA[i] = 0x8
			i = encodeVarintAsyncOps(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.NewAsyncOps) > 0 {
		for iNdEx := len(m.NewAsyncOps) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.NewAsyncOps[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAsyncOps(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *AsyncOp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AsyncOp) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AsyncOp) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Source) > 0 {
		i -= len(m.Source)
		copy(dAtA[i:], m.Source)
		i = encodeVarintAsyncOps(dAtA, i, uint64(len(m.Source)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Metadata != nil {
		{
			size, err := m.Metadata.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAsyncOps(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Id != nil {
		{
			size, err := m.Id.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAsyncOps(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Stats) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Stats) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Stats) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PollStats != nil {
		{
			size, err := m.PollStats.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAsyncOps(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if m.TaskId != nil {
		{
			size, err := m.TaskId.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAsyncOps(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.ResourceId != nil {
		{
			size, err := m.ResourceId.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAsyncOps(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.DroppedAt != nil {
		{
			size, err := m.DroppedAt.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAsyncOps(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.CreatedAt != nil {
		{
			size, err := m.CreatedAt.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAsyncOps(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintAsyncOps(dAtA []byte, offset int, v uint64) int {
	offset -= sovAsyncOps(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *AsyncOpUpdate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.NewAsyncOps) > 0 {
		for _, e := range m.NewAsyncOps {
			l = e.Size()
			n += 1 + l + sovAsyncOps(uint64(l))
		}
	}
	if len(m.StatsUpdate) > 0 {
		for k, v := range m.StatsUpdate {
			_ = k
			_ = v
			l = 0
			if v != nil {
				l = v.Size()
				l += 1 + sovAsyncOps(uint64(l))
			}
			mapEntrySize := 1 + sovAsyncOps(uint64(k)) + l
			n += mapEntrySize + 1 + sovAsyncOps(uint64(mapEntrySize))
		}
	}
	return n
}

func (m *AsyncOp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != nil {
		l = m.Id.Size()
		n += 1 + l + sovAsyncOps(uint64(l))
	}
	if m.Metadata != nil {
		l = m.Metadata.Size()
		n += 1 + l + sovAsyncOps(uint64(l))
	}
	l = len(m.Source)
	if l > 0 {
		n += 1 + l + sovAsyncOps(uint64(l))
	}
	return n
}

func (m *Stats) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CreatedAt != nil {
		l = m.CreatedAt.Size()
		n += 1 + l + sovAsyncOps(uint64(l))
	}
	if m.DroppedAt != nil {
		l = m.DroppedAt.Size()
		n += 1 + l + sovAsyncOps(uint64(l))
	}
	if m.ResourceId != nil {
		l = m.ResourceId.Size()
		n += 1 + l + sovAsyncOps(uint64(l))
	}
	if m.TaskId != nil {
		l = m.TaskId.Size()
		n += 1 + l + sovAsyncOps(uint64(l))
	}
	if m.PollStats != nil {
		l = m.PollStats.Size()
		n += 1 + l + sovAsyncOps(uint64(l))
	}
	return n
}

func sovAsyncOps(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAsyncOps(x uint64) (n int) {
	return sovAsyncOps(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *AsyncOpUpdate) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForNewAsyncOps := "[]*AsyncOp{"
	for _, f := range this.NewAsyncOps {
		repeatedStringForNewAsyncOps += strings.Replace(f.String(), "AsyncOp", "AsyncOp", 1) + ","
	}
	repeatedStringForNewAsyncOps += "}"
	keysForStatsUpdate := make([]uint64, 0, len(this.StatsUpdate))
	for k, _ := range this.StatsUpdate {
		keysForStatsUpdate = append(keysForStatsUpdate, k)
	}
	github_com_gogo_protobuf_sortkeys.Uint64s(keysForStatsUpdate)
	mapStringForStatsUpdate := "map[uint64]*Stats{"
	for _, k := range keysForStatsUpdate {
		mapStringForStatsUpdate += fmt.Sprintf("%v: %v,", k, this.StatsUpdate[k])
	}
	mapStringForStatsUpdate += "}"
	s := strings.Join([]string{`&AsyncOpUpdate{`,
		`NewAsyncOps:` + repeatedStringForNewAsyncOps + `,`,
		`StatsUpdate:` + mapStringForStatsUpdate + `,`,
		`}`,
	}, "")
	return s
}
func (this *AsyncOp) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&AsyncOp{`,
		`Id:` + strings.Replace(fmt.Sprintf("%v", this.Id), "Id", "common.Id", 1) + `,`,
		`Metadata:` + strings.Replace(fmt.Sprintf("%v", this.Metadata), "MetaId", "common.MetaId", 1) + `,`,
		`Source:` + fmt.Sprintf("%v", this.Source) + `,`,
		`}`,
	}, "")
	return s
}
func (this *Stats) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Stats{`,
		`CreatedAt:` + strings.Replace(fmt.Sprintf("%v", this.CreatedAt), "Timestamp", "timestamp.Timestamp", 1) + `,`,
		`DroppedAt:` + strings.Replace(fmt.Sprintf("%v", this.DroppedAt), "Timestamp", "timestamp.Timestamp", 1) + `,`,
		`ResourceId:` + strings.Replace(fmt.Sprintf("%v", this.ResourceId), "Id", "common.Id", 1) + `,`,
		`TaskId:` + strings.Replace(fmt.Sprintf("%v", this.TaskId), "Id", "common.Id", 1) + `,`,
		`PollStats:` + strings.Replace(fmt.Sprintf("%v", this.PollStats), "PollStats", "common.PollStats", 1) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringAsyncOps(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *AsyncOpUpdate) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAsyncOps
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AsyncOpUpdate: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AsyncOpUpdate: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewAsyncOps", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAsyncOps
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAsyncOps
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAsyncOps
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NewAsyncOps = append(m.NewAsyncOps, &AsyncOp{})
			if err := m.NewAsyncOps[len(m.NewAsyncOps)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StatsUpdate", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAsyncOps
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAsyncOps
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAsyncOps
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.StatsUpdate == nil {
				m.StatsUpdate = make(map[uint64]*Stats)
			}
			var mapkey uint64
			var mapvalue *Stats
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowAsyncOps
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowAsyncOps
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
				} else if fieldNum == 2 {
					var mapmsglen int
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowAsyncOps
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapmsglen |= int(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					if mapmsglen < 0 {
						return ErrInvalidLengthAsyncOps
					}
					postmsgIndex := iNdEx + mapmsglen
					if postmsgIndex < 0 {
						return ErrInvalidLengthAsyncOps
					}
					if postmsgIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = &Stats{}
					if err := mapvalue.Unmarshal(dAtA[iNdEx:postmsgIndex]); err != nil {
						return err
					}
					iNdEx = postmsgIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipAsyncOps(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthAsyncOps
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.StatsUpdate[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAsyncOps(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAsyncOps
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthAsyncOps
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AsyncOp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAsyncOps
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AsyncOp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AsyncOp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAsyncOps
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAsyncOps
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAsyncOps
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Id == nil {
				m.Id = &common.Id{}
			}
			if err := m.Id.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metadata", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAsyncOps
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAsyncOps
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAsyncOps
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Metadata == nil {
				m.Metadata = &common.MetaId{}
			}
			if err := m.Metadata.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Source", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAsyncOps
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAsyncOps
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAsyncOps
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Source = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAsyncOps(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAsyncOps
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthAsyncOps
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Stats) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAsyncOps
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Stats: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Stats: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAsyncOps
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAsyncOps
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAsyncOps
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CreatedAt == nil {
				m.CreatedAt = &timestamp.Timestamp{}
			}
			if err := m.CreatedAt.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DroppedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAsyncOps
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAsyncOps
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAsyncOps
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DroppedAt == nil {
				m.DroppedAt = &timestamp.Timestamp{}
			}
			if err := m.DroppedAt.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResourceId", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAsyncOps
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAsyncOps
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAsyncOps
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ResourceId == nil {
				m.ResourceId = &common.Id{}
			}
			if err := m.ResourceId.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskId", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAsyncOps
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAsyncOps
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAsyncOps
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TaskId == nil {
				m.TaskId = &common.Id{}
			}
			if err := m.TaskId.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PollStats", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAsyncOps
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAsyncOps
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAsyncOps
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PollStats == nil {
				m.PollStats = &common.PollStats{}
			}
			if err := m.PollStats.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAsyncOps(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAsyncOps
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthAsyncOps
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAsyncOps(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAsyncOps
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAsyncOps
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAsyncOps
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAsyncOps
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthAsyncOps
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowAsyncOps
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipAsyncOps(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthAsyncOps
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthAsyncOps = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAsyncOps   = fmt.Errorf("proto: integer overflow")
)
