// This file is autogenerated. DO NOT EDIT.
//
// Generated by "thema lineage gen" from lineage defined in storage.cue

package storage

// Storage defines model for storage.
type Storage struct {
	Common struct {
		Storage struct {
			S3 *struct {
				Region *string `json:"region,omitempty"`
			} `json:"s3,omitempty"`
		} `json:"storage"`
	} `json:"common"`
}
